### ISSUE TITLE
Workspaces start from 0

### ISSUE THREAD

**Issue by ajnisbet** [lukeshimanuki/i3-grid#1]
The default workspace for i3 is 1, while i3-grid starts at 0. As a result, you don't start in the top-left workspace, which is unexpected.

Happy do to a pull request if you like, probably just a change to `_getCoord`.

**Comment by lukeshimanuki** [comment]
Yeah, I usually just tell i3 to switch to workspace 0 on startup, since it makes more sense intuitively for 0 to be the top-left workspace.

You're welcome to change it if you like. You'd probably just have to change `_getID` to return 1 more than what it currently does, and change `_getCoord` to use `ID - 1` in place of `ID`.

**Comment by ajnisbet** [comment]
Ah right, didn't think of that, am new to i3. Adding `exec --no-startup-id i3-msg workspace 0` to `.i3/config` is exactly what I want.

Thanks so much for i3-grid!
